version: '3.8'
services:
  goravel-db:
    image: postgres:latest
    container_name: goravel-db
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - Heepoke

  redis:
    image: redis:latest
    container_name: goravel-redis
    hostname: redis
    env_file:
      - .env
    command: ["redis-server", "--include", "/usr/local/etc/redis/redis.conf", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
     - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis-data:/var/lib/redis
      - "./pkg/redis/conf/generate.conf:/usr/local/etc/redis/redis.conf"
    environment:
      REDIS_PASSWORD: 
    networks:
      - Heepoke

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goravel-api
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - goravel-db
      - redis
    networks:
      - Heepoke

volumes:
  redis-data:

networks:
  Heepoke:
    driver: bridge